/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmlakKategoriRouteImport } from './routes/emlak.$kategori'
import { Route as IlanIdRouteImport } from './routes/ilan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakKategoriRoute = EmlakKategoriRouteImport.update({
  id: '/emlak/$kategori',
  path: '/emlak/$kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanIdRoute = IlanIdRouteImport.update({
  id: '/ilan/$id',
  path: '/ilan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emlak/$kategori': typeof EmlakKategoriRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emlak/$kategori': typeof EmlakKategoriRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emlak/$kategori': typeof EmlakKategoriRoute
  '/ilan/$id': typeof IlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/emlak/$kategori' | '/ilan/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/emlak/$kategori' | '/ilan/$id'
  id: '__root__' | '/' | '/emlak/$kategori' | '/ilan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmlakKategoriRoute: typeof EmlakKategoriRoute
  IlanIdRoute: typeof IlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak/$kategori': {
      id: '/emlak/$kategori'
      path: '/emlak/$kategori'
      fullPath: '/emlak/$kategori'
      preLoaderRoute: typeof EmlakKategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$id': {
      id: '/ilan/$id'
      path: '/ilan/$id'
      fullPath: '/ilan/$id'
      preLoaderRoute: typeof IlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmlakKategoriRoute: EmlakKategoriRoute,
  IlanIdRoute: IlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
